# Generated by Django 4.1.5 on 2024-01-28 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iess', models.IntegerField(default=1003)),
                ('tipoIdentificacion', models.IntegerField(default=1)),
                ('identificacion', models.CharField(max_length=255, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[(1, 'HOMBRE'), (2, 'MUJER')], default='Seleccione Sexo', max_length=1)),
                ('fechaNacimiento', models.DateField(blank=True, null=True)),
                ('carrera', models.ForeignKey(default='Seleccione Carrera', on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.carrera')),
            ],
        ),
    ]
