# Generated by Django 4.1.5 on 2024-01-28 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='ESTUDIANTES',
        ),
    ]
