# Generated by Django 4.1.5 on 2024-04-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0003_remove_estudiantes_carrera_remove_estudiantes_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_carrera', models.CharField(choices=[(1, 'AGROINDUSTRIA'), (2, 'INGENIERIA AMBIENTAL'), (3, 'COMPUTACION'), (4, 'TURISMO'), (5, 'MEDICINA VETERINARIA'), (6, 'INGENIERIA AGRICOLA'), (7, 'ADMINISTRACION DE EMPRESAS'), (8, 'ADMINISTRACION PUBLICA'), (9, 'ELECTRONICA Y AUTOMATIZACION'), (10, 'INGENIERIA EN RIESGOS DE DESASTRES'), (11, 'INGENIERIA AGROFORESTAL'), (12, 'INGENIERIA DE LA PRODUCCION')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.DateField(auto_now=True, null=True)),
                ('fecha', models.DateField(auto_now=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ESTUDIANTES',
            new_name='estudiante',
        ),
    ]
