# Generated by Django 4.1.5 on 2024-04-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0004_carrera_registro_rename_estudiantes_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.carrera'),
        ),
        migrations.AddField(
            model_name='registro',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.estudiante'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='motivo',
            field=models.CharField(max_length=255),
        ),
    ]
