# Generated by Django 4.1.5 on 2024-04-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0005_registro_carrera_registro_estudiante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='nombre_carrera',
            field=models.CharField(choices=[('1', 'AGROINDUSTRIA'), ('2', 'INGENIERIA AMBIENTAL'), (3, 'COMPUTACION'), (4, 'TURISMO'), (5, 'MEDICINA VETERINARIA'), (6, 'INGENIERIA AGRICOLA'), (7, 'ADMINISTRACION DE EMPRESAS'), (8, 'ADMINISTRACION PUBLICA'), (9, 'ELECTRONICA Y AUTOMATIZACION'), (10, 'INGENIERIA EN RIESGOS DE DESASTRES'), (11, 'INGENIERIA AGROFORESTAL'), (12, 'INGENIERIA DE LA PRODUCCION')], max_length=1),
        ),
    ]
