# Generated by Django 4.1.5 on 2024-04-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0006_alter_carrera_nombre_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='fechaNacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='iess',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='tipoIdentificacion',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_materno',
            field=models.CharField(default='Vera', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apellido_paterno',
            field=models.CharField(default='Lucas', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(default='1312196684', max_length=10),
        ),
        migrations.AlterField(
            model_name='carrera',
            name='nombre_carrera',
            field=models.CharField(choices=[('1', 'AGROINDUSTRIA'), ('2', 'INGENIERIA AMBIENTAL'), ('3', 'COMPUTACION'), ('4', 'TURISMO'), ('5', 'MEDICINA VETERINARIA'), ('6', 'INGENIERIA AGRICOLA'), ('7', 'ADMINISTRACION DE EMPRESAS'), ('8', 'ADMINISTRACION PUBLICA'), ('9', 'ELECTRONICA Y AUTOMATIZACION'), ('10', 'INGENIERIA EN RIESGOS DE DESASTRES'), ('11', 'INGENIERIA AGROFORESTAL'), ('12', 'INGENIERIA DE LA PRODUCCION')], max_length=2),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registro',
            name='motivo',
            field=models.CharField(choices=[('1', 'APOYO SOCIOECONOMICO (BECAS)'), ('2', 'ORIENTACIÓN VOCACIONAL Y DESARROLLO'), ('3', 'ATENCIÓN PSICOLÓGICA'), ('4', 'SEGURO ESTUDIANTIL'), ('5', 'MEDIACIÓN'), ('6', 'TRABAJO SOCIAL'), ('7', 'INCLUSIÓN'), ('8', 'ATENCIÓN MÉDICA'), ('9', 'ATENCIÓN ODONTOLÓGICA'), ('10', 'DEPORTE'), ('11', 'MÚSICA'), ('12', 'DANZA')], max_length=2),
        ),
    ]
