# Generated by Django 4.1.5 on 2024-04-05 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0008_alter_carrera_nombre_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.estudiante'),
        ),
    ]
