# Generated by Django 4.1.5 on 2024-04-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0011_alter_estudiante_apellido_materno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='sexo',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('1', 'HOMBRE'), ('2', 'MUJER'), ('3', 'NO BINARIO')], default=1, max_length=2),
        ),
    ]
