# Generated by Django 4.1.5 on 2024-04-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0012_remove_registro_sexo_estudiante_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(choices=[('1', 'HOMBRE'), ('2', 'MUJER'), ('3', 'NO BINARIO')], max_length=2),
        ),
    ]
