# Generated by Django 4.1.5 on 2024-04-07 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0016_rename_registro_atencion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atencion',
            name='carrera',
        ),
        migrations.AddField(
            model_name='carrera',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.estudiante'),
        ),
    ]
