# Generated by Django 4.1.5 on 2024-04-07 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0018_remove_book_author_remove_book_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estudiante',
            field=models.ForeignKey(default='gary', on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.carrera'),
        ),
    ]
