# Generated by Django 4.1.5 on 2024-04-07 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0019_alter_estudiante_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.estudiante'),
        ),
    ]
