# Generated by Django 4.1.5 on 2024-04-07 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0020_alter_atencion_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='estudiante',
            field=models.ForeignKey(default=11220, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.carrera'),
        ),
    ]
