# Generated by Django 4.1.5 on 2024-04-08 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0021_alter_estudiante_estudiante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='estudiante',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.carrera'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='estudiante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.estudiante'),
        ),
    ]
