# Generated by Django 4.1.5 on 2024-04-11 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0024_alter_atencion_estudiante_alter_estudiante_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encuesta', models.CharField(choices=[('1', 'MUY BUENA'), ('2', 'BUENA'), ('3', 'REGULAR')], max_length=2)),
                ('fecha', models.DateField(auto_now=True)),
                ('atencion', models.ForeignKey(default='Buscar', on_delete=django.db.models.deletion.CASCADE, to='AtencionEstudiantes.atencion')),
            ],
        ),
    ]
