# Generated by Django 4.1.5 on 2024-04-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AtencionEstudiantes', '0026_atencion_encuesta_delete_encuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='encuesta',
            field=models.CharField(blank=True, choices=[('1', 'MUY BUENA'), ('2', 'BUENA'), ('3', 'REGULAR')], default='___', max_length=2, null=True),
        ),
    ]
