# Generated by Django 4.1.5 on 2023-09-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=50)),
            ],
        ),
    ]
