# Generated by Django 4.1.5 on 2023-09-11 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0003_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nivel',
            name='carrera',
        ),
    ]
