# Generated by Django 4.1.5 on 2023-09-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_remove_nivel_carrera'),
    ]

    operations = [
        migrations.AddField(
            model_name='nivel',
            name='carrera_nivel',
            field=models.ManyToManyField(to='procesos.carrera'),
        ),
    ]
