# Generated by Django 4.1.5 on 2024-01-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0005_nivel_carrera_nivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nivel',
            old_name='carrera_nivel',
            new_name='codigo',
        ),
    ]
