# Generated by Django 4.1.5 on 2023-02-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expediente', models.CharField(max_length=255, unique=True)),
                ('fechainicio', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SeccionSucceion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccionsubseccion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=255, unique=True, verbose_name='Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipodocumento', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoexpediente', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubSerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subserie', models.CharField(max_length=255, unique=True, verbose_name='Sub Serie')),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.serie')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True, verbose_name='Recibido')),
                ('codigo', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('detalle', models.TextField(max_length=255)),
                ('hojas', models.IntegerField(default=1)),
                ('pendiente', models.BooleanField(default=True, max_length=1, verbose_name='Pendiente')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.departamento', verbose_name='Departamento')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('departamentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.departamento')),
                ('documentoexpediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.documento')),
                ('expedientedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.expediente')),
                ('subseriedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.subserie')),
                ('tipodocumentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipodocumento')),
                ('tipoexpedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipoexpediente')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='seccionsubdepartamento',
            field=models.ManyToManyField(to='GestionDocumentalApp.seccionsucceion'),
        ),
    ]
