# Generated by Django 4.1.5 on 2023-02-27 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocumentalApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleExpediente',
        ),
    ]
