# Generated by Django 4.1.5 on 2023-02-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocumentalApp', '0002_delete_detalleexpediente'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleExpediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechafin', models.DateField(blank=True, null=True)),
                ('departamentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.departamento')),
                ('documentoexpediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.documento')),
                ('expedientedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.expediente')),
                ('subseriedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.subserie')),
                ('tipodocumentodetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipodocumento')),
                ('tipoexpedetalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipoexpediente')),
            ],
        ),
    ]
