# Generated by Django 4.1.5 on 2023-02-27 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocumentalApp', '0005_rename_formato_documento_tipodocumento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='departamento',
        ),
    ]
