# Generated by Django 4.1.5 on 2023-02-28 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocumentalApp', '0008_remove_documento_estado_alter_documento_electronico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estadotramite',
            field=models.CharField(choices=[(1, 'Recibido'), (2, 'Atendido'), (3, 'Archivado'), (4, 'S/N')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipodocumento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='GestionDocumentalApp.tipodocumento'),
        ),
    ]
