# Generated by Django 4.1.5 on 2023-09-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionDocumentalApp', '0009_alter_documento_estadotramite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='detalle',
            new_name='descripcion',
        ),
        migrations.AlterField(
            model_name='documento',
            name='estadotramite',
            field=models.CharField(choices=[('1', 'Recibido'), (2, 'Atendido'), (3, 'Archivado'), (4, 'S/N')], default=4, max_length=1),
        ),
    ]
